### ISSUE TITLE
Error AchillesBeanMappingException when running in prod mod 

### ISSUE THREAD

**Issue by p-narola** [doanduyhai/killrchat#25]
Hi,

   When I am running killrchat branch "AchilllesDemo", I am running into following issue. Do you know what could be the issue?

Caused by: info.archinnov.achilles.exception.AchillesBeanMappingException: Data type 'set<frozen<killrchat.user_authority>>' for column 'authorities' of entity 'class com.datastax.demo.killrchat.entity.PersistentTokenEntity' does not match type in live schema 'set<text>'
	at info.archinnov.achilles.validation.Validator.validateBeanMappingTrue(Validator.java:125)
	at info.archinnov.achilles.internals.schema.SchemaValidator.validateColumns(SchemaValidator.java:124)
	at info.archinnov.achilles.internals.metamodel.AbstractEntityProperty.validateSchema(AbstractEntityProperty.java:348)
	at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.lambda$validateSchema$465(AbstractManagerFactory.java:186)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.validateSchema(AbstractManagerFactory.java:186)
	at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.bootstrap(AbstractManagerFactory.java:121)
	at info.archinnov.achilles.generated.ManagerFactory.<init>(ManagerFactory.java:56)
	at info.archinnov.achilles.generated.ManagerFactoryBuilder.build(ManagerFactoryBuilder.java:38)
	at com.datastax.demo.killrchat.configuration.CassandraConfiguration.cassandraNativeClusterProduction(CassandraConfiguration.java:68)
	at com.datastax.demo.killrchat.configuration.CassandraConfiguration$$EnhancerBySpringCGLIB$$3bc3981b.CGLIB$cassandraNativeClusterProduction$0(<generated>)
	at com.datastax.demo.killrchat.configuration.CassandraConfiguration$$EnhancerBySpringCGLIB$$3bc3981b$$FastClassBySpringCGLIB$$5b859374.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at com.datastax.demo.killrchat.configuration.CassandraConfiguration$$EnhancerBySpringCGLIB$$3bc3981b.cassandraNativeClusterProduction(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)

**Comment by doanduyhai** [comment]
Humm it's an old issue, I will upgrade Achilles for KillrChat

**Comment by p-narola** [comment]
I have was trying this in AchillesDemo branch only which has dependency on Achilles Version 5.1.5.
